version: '3.2'
services:
  web:
    build: .
    command: yarn run start:server
    ports:
      - 3000:3000
    volumes:
      - .:/game_on
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  postgres:
    image: postgres:11.2
    volumes:
      - postgres_game_on:/var/lib/postgresql/data

volumes:
  game_on:
  postgres_game_on:
